// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGHfljkoPvBxT0N2zhyavbXPXEWlU_5iY',
    appId: '1:203321834890:web:aa25cfd0f9b7a5461f1c73',
    messagingSenderId: '203321834890',
    projectId: 'messenger-app-b7eb7',
    authDomain: 'messenger-app-b7eb7.firebaseapp.com',
    storageBucket: 'messenger-app-b7eb7.appspot.com',
    measurementId: 'G-ECF4155QPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp9kR3kk8CSQML5MsdqFpK4o2i1YTD6Ok',
    appId: '1:203321834890:android:3b0a52ccf66f0a3b1f1c73',
    messagingSenderId: '203321834890',
    projectId: 'messenger-app-b7eb7',
    storageBucket: 'messenger-app-b7eb7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzQF_Dp029QZoSvJwruB2QonysSgK_Hv4',
    appId: '1:203321834890:ios:aaf4b7a3071ac3ba1f1c73',
    messagingSenderId: '203321834890',
    projectId: 'messenger-app-b7eb7',
    storageBucket: 'messenger-app-b7eb7.appspot.com',
    iosClientId: '203321834890-jjvbr3td7u7lassfi3dj1fhujprli46a.apps.googleusercontent.com',
    iosBundleId: 'com.example.messengerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzQF_Dp029QZoSvJwruB2QonysSgK_Hv4',
    appId: '1:203321834890:ios:aaf4b7a3071ac3ba1f1c73',
    messagingSenderId: '203321834890',
    projectId: 'messenger-app-b7eb7',
    storageBucket: 'messenger-app-b7eb7.appspot.com',
    iosClientId: '203321834890-jjvbr3td7u7lassfi3dj1fhujprli46a.apps.googleusercontent.com',
    iosBundleId: 'com.example.messengerApp',
  );
}
